version: '3'
services:

 web1:
  build:
   context: .
   dockerfile: DockerCentosImage
  container_name: web1
  restart: unless-stopped
  tty: true   
  networks:
   - my-project
  privileged: true
  tmpfs:
    - /run
    - /run/lock
    - /tmp
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

 web2:
  build:
   context: .
   dockerfile: DockerCentosImage
  container_name: web2
  restart: unless-stopped
  tty: true  
  networks:
   - my-project
  privileged: true
  tmpfs:
    - /run
    - /run/lock
    - /tmp
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

 webtest:
  build:
   context: .
   dockerfile: DockerCentosImage
  container_name: webtest
  restart: unless-stopped
  tty: true  
  networks:
   - my-project
  privileged: true
  tmpfs:
    - /run
    - /run/lock
    - /tmp
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

networks:
 my-project:
  driver: bridge
